# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1920, 1080)
        Frame.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(90, 145, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.main_lb_Date = QtWidgets.QLabel(Frame)
        self.main_lb_Date.setGeometry(QtCore.QRect(1020, 500, 56, 16))
        self.main_lb_Date.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.main_lb_Date.setObjectName("main_lb_Date")
        self.main_lb_time = QtWidgets.QLabel(Frame)
        self.main_lb_time.setGeometry(QtCore.QRect(1020, 470, 56, 16))
        self.main_lb_time.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.main_lb_time.setObjectName("main_lb_time")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(960, 90, 371, 331))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/estLogo.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.m_frame = QtWidgets.QFrame(Frame)
        self.m_frame.setGeometry(QtCore.QRect(10, 10, 951, 621))
        self.m_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.m_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.m_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m_frame.setLineWidth(0)
        self.m_frame.setMidLineWidth(4)
        self.m_frame.setObjectName("m_frame")
        self.frame_1 = QtWidgets.QFrame(self.m_frame)
        self.frame_1.setGeometry(QtCore.QRect(10, 30, 471, 511))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_1.setPalette(palette)
        self.frame_1.setAutoFillBackground(False)
        self.frame_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setObjectName("frame_1")
        self.Img_label = QtWidgets.QLabel(self.frame_1)
        self.Img_label.setGeometry(QtCore.QRect(60, 100, 311, 311))
        self.Img_label.setMinimumSize(QtCore.QSize(311, 251))
        self.Img_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Img_label.setMouseTracking(True)
        self.Img_label.setText("")
        self.Img_label.setPixmap(QtGui.QPixmap("Images/pNewProd.bmp"))
        self.Img_label.setScaledContents(True)
        self.Img_label.setObjectName("Img_label")
        self.main_cross = QtWidgets.QLabel(self.frame_1)
        self.main_cross.setGeometry(QtCore.QRect(40, 100, 41, 41))
        self.main_cross.setText("")
        self.main_cross.setPixmap(QtGui.QPixmap("Images/1cross.png"))
        self.main_cross.setScaledContents(True)
        self.main_cross.setObjectName("main_cross")
        self.main_circle = QtWidgets.QLabel(self.frame_1)
        self.main_circle.setGeometry(QtCore.QRect(40, 80, 41, 41))
        self.main_circle.setText("")
        self.main_circle.setPixmap(QtGui.QPixmap("Images/circle_lGreen.png"))
        self.main_circle.setScaledContents(True)
        self.main_circle.setObjectName("main_circle")
        self.main_lb_program = QtWidgets.QLabel(self.frame_1)
        self.main_lb_program.setGeometry(QtCore.QRect(40, 10, 151, 41))
        self.main_lb_program.setObjectName("main_lb_program")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_1)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 430, 311, 21))
        self.horizontalSlider.setMaximum(1000)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(self.frame_1)
        self.verticalSlider.setGeometry(QtCore.QRect(390, 100, 21, 311))
        self.verticalSlider.setMaximum(1000)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(True)
        self.verticalSlider.setObjectName("verticalSlider")
        self.Img_label.raise_()
        self.main_circle.raise_()
        self.main_cross.raise_()
        self.main_lb_program.raise_()
        self.horizontalSlider.raise_()
        self.verticalSlider.raise_()
        self.frame_2 = QtWidgets.QFrame(self.m_frame)
        self.frame_2.setGeometry(QtCore.QRect(490, 30, 451, 371))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.main_lb_state = QtWidgets.QLabel(self.frame_2)
        self.main_lb_state.setGeometry(QtCore.QRect(40, 20, 111, 31))
        self.main_lb_state.setObjectName("main_lb_state")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 90, 56, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 56, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 131, 31))
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 250, 431, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 20, 91, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/arowDown.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Images/arowUp.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(70, 68))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoDefault(True)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 20, 101, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Drill1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("Images/Drill2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(70, 67))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setAutoDefault(True)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame = QtWidgets.QFrame(self.m_frame)
        self.frame.setGeometry(QtCore.QRect(490, 430, 451, 71))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 111, 41))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.pushButton.setText("Manual")
        self.pushButton.setIconSize(QtCore.QSize(51, 33))
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 20, 111, 41))
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.pushButton_2.setText("In/ Out")
        self.pushButton_2.setIconSize(QtCore.QSize(51, 33))
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 20, 111, 41))
        self.pushButton_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.pushButton_3.setText("Data")
        self.pushButton_3.setIconSize(QtCore.QSize(51, 33))
        self.pushButton_3.setAutoDefault(False)
        self.pushButton_3.setDefault(False)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_4 = QtWidgets.QFrame(Frame)
        self.frame_4.setGeometry(QtCore.QRect(1290, 10, 441, 621))
        self.frame_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setLineWidth(0)
        self.frame_4.setMidLineWidth(4)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(40, 70, 151, 51))
        self.frame_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(40, 130, 151, 51))
        self.frame_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setGeometry(QtCore.QRect(40, 190, 151, 51))
        self.frame_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(40, 250, 151, 51))
        self.frame_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_12.setObjectName("label_12")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setGeometry(QtCore.QRect(40, 370, 151, 51))
        self.frame_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_23 = QtWidgets.QLabel(self.frame_9)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_23.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_24.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_24.setObjectName("label_24")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setGeometry(QtCore.QRect(40, 430, 151, 51))
        self.frame_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_25 = QtWidgets.QLabel(self.frame_10)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_25.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_26.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_26.setObjectName("label_26")
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setGeometry(QtCore.QRect(40, 310, 151, 51))
        self.frame_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_27 = QtWidgets.QLabel(self.frame_12)
        self.label_27.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_27.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_12)
        self.label_28.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_28.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_28.setObjectName("label_28")
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        self.frame_13.setGeometry(QtCore.QRect(40, 490, 151, 51))
        self.frame_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_29 = QtWidgets.QLabel(self.frame_13)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_29.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_30.setObjectName("label_30")
        self.frame_14 = QtWidgets.QFrame(self.frame_4)
        self.frame_14.setGeometry(QtCore.QRect(40, 550, 151, 51))
        self.frame_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_31 = QtWidgets.QLabel(self.frame_14)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_31.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_31.setScaledContents(True)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_14)
        self.label_32.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_32.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_32.setObjectName("label_32")
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(260, 130, 151, 51))
        self.frame_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_18.setObjectName("label_18")
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setGeometry(QtCore.QRect(260, 370, 151, 51))
        self.frame_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_33 = QtWidgets.QLabel(self.frame_15)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_33.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_33.setText("")
        self.label_33.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_33.setScaledContents(True)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame_15)
        self.label_34.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_34.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_34.setObjectName("label_34")
        self.frame_16 = QtWidgets.QFrame(self.frame_4)
        self.frame_16.setGeometry(QtCore.QRect(260, 430, 151, 51))
        self.frame_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_35 = QtWidgets.QLabel(self.frame_16)
        self.label_35.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_35.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_16)
        self.label_36.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_36.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_36.setObjectName("label_36")
        self.frame_17 = QtWidgets.QFrame(self.frame_4)
        self.frame_17.setGeometry(QtCore.QRect(260, 190, 151, 51))
        self.frame_17.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_37 = QtWidgets.QLabel(self.frame_17)
        self.label_37.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_37.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_17)
        self.label_38.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_38.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_38.setObjectName("label_38")
        self.frame_18 = QtWidgets.QFrame(self.frame_4)
        self.frame_18.setGeometry(QtCore.QRect(260, 70, 151, 51))
        self.frame_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_39 = QtWidgets.QLabel(self.frame_18)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_39.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_39.setScaledContents(True)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_18)
        self.label_40.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_40.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_40.setObjectName("label_40")
        self.frame_19 = QtWidgets.QFrame(self.frame_4)
        self.frame_19.setGeometry(QtCore.QRect(260, 310, 151, 51))
        self.frame_19.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_41 = QtWidgets.QLabel(self.frame_19)
        self.label_41.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_41.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_41.setText("")
        self.label_41.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_41.setScaledContents(True)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_19)
        self.label_42.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_42.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_42.setObjectName("label_42")
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setGeometry(QtCore.QRect(260, 250, 151, 51))
        self.frame_20.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.label_43 = QtWidgets.QLabel(self.frame_20)
        self.label_43.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_43.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.label_43.setScaledContents(True)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_20)
        self.label_44.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_44.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_44.setObjectName("label_44")
        self.main_lb_state_2 = QtWidgets.QLabel(self.frame_4)
        self.main_lb_state_2.setGeometry(QtCore.QRect(40, 20, 111, 31))
        self.main_lb_state_2.setObjectName("main_lb_state_2")
        self.main_lb_state_3 = QtWidgets.QLabel(self.frame_4)
        self.main_lb_state_3.setGeometry(QtCore.QRect(260, 20, 111, 31))
        self.main_lb_state_3.setObjectName("main_lb_state_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 540, 151, 61))
        self.pushButton_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.pushButton_6.setText("Close")
        self.pushButton_6.setIconSize(QtCore.QSize(51, 33))
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_21 = QtWidgets.QFrame(Frame)
        self.frame_21.setGeometry(QtCore.QRect(10, 630, 951, 351))
        self.frame_21.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_21.setMidLineWidth(4)
        self.frame_21.setObjectName("frame_21")
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setGeometry(QtCore.QRect(40, 90, 261, 71))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_45 = QtWidgets.QLabel(self.frame_23)
        self.label_45.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_45.setObjectName("label_45")
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        self.frame_22.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_22.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_46 = QtWidgets.QLabel(self.frame_22)
        self.label_46.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_46.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_46.setObjectName("label_46")
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        self.frame_24.setGeometry(QtCore.QRect(40, 150, 261, 71))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_49 = QtWidgets.QLabel(self.frame_24)
        self.label_49.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_49.setObjectName("label_49")
        self.frame_26 = QtWidgets.QFrame(self.frame_24)
        self.frame_26.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_26.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.label_50 = QtWidgets.QLabel(self.frame_26)
        self.label_50.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_50.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_50.setObjectName("label_50")
        self.frame_27 = QtWidgets.QFrame(self.frame_21)
        self.frame_27.setGeometry(QtCore.QRect(40, 210, 261, 71))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_51 = QtWidgets.QLabel(self.frame_27)
        self.label_51.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_51.setObjectName("label_51")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_28.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_52 = QtWidgets.QLabel(self.frame_28)
        self.label_52.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_52.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_52.setObjectName("label_52")
        self.frame_29 = QtWidgets.QFrame(self.frame_21)
        self.frame_29.setGeometry(QtCore.QRect(40, 270, 261, 71))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_55 = QtWidgets.QLabel(self.frame_29)
        self.label_55.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_55.setObjectName("label_55")
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_31.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label_56 = QtWidgets.QLabel(self.frame_31)
        self.label_56.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_56.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_56.setObjectName("label_56")
        self.frame_32 = QtWidgets.QFrame(self.frame_21)
        self.frame_32.setGeometry(QtCore.QRect(300, 210, 261, 71))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_65 = QtWidgets.QLabel(self.frame_32)
        self.label_65.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_65.setObjectName("label_65")
        self.frame_34 = QtWidgets.QFrame(self.frame_32)
        self.frame_34.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_34.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.label_66 = QtWidgets.QLabel(self.frame_34)
        self.label_66.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_66.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_66.setObjectName("label_66")
        self.frame_36 = QtWidgets.QFrame(self.frame_21)
        self.frame_36.setGeometry(QtCore.QRect(300, 270, 261, 71))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_67 = QtWidgets.QLabel(self.frame_36)
        self.label_67.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_67.setObjectName("label_67")
        self.frame_38 = QtWidgets.QFrame(self.frame_36)
        self.frame_38.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_38.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_68 = QtWidgets.QLabel(self.frame_38)
        self.label_68.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_68.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_68.setObjectName("label_68")
        self.frame_40 = QtWidgets.QFrame(self.frame_21)
        self.frame_40.setGeometry(QtCore.QRect(300, 90, 261, 71))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_69 = QtWidgets.QLabel(self.frame_40)
        self.label_69.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_69.setObjectName("label_69")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_41.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.label_70 = QtWidgets.QLabel(self.frame_41)
        self.label_70.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_70.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_70.setObjectName("label_70")
        self.frame_42 = QtWidgets.QFrame(self.frame_21)
        self.frame_42.setGeometry(QtCore.QRect(300, 150, 261, 71))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.label_71 = QtWidgets.QLabel(self.frame_42)
        self.label_71.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_71.setObjectName("label_71")
        self.frame_43 = QtWidgets.QFrame(self.frame_42)
        self.frame_43.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_43.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.label_72 = QtWidgets.QLabel(self.frame_43)
        self.label_72.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_72.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_72.setObjectName("label_72")
        self.frame_44 = QtWidgets.QFrame(self.frame_21)
        self.frame_44.setGeometry(QtCore.QRect(560, 90, 261, 71))
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.label_89 = QtWidgets.QLabel(self.frame_44)
        self.label_89.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_89.setObjectName("label_89")
        self.frame_61 = QtWidgets.QFrame(self.frame_44)
        self.frame_61.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_61.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.label_90 = QtWidgets.QLabel(self.frame_61)
        self.label_90.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_90.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_90.setObjectName("label_90")
        self.frame_62 = QtWidgets.QFrame(self.frame_21)
        self.frame_62.setGeometry(QtCore.QRect(560, 150, 261, 71))
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.label_91 = QtWidgets.QLabel(self.frame_62)
        self.label_91.setGeometry(QtCore.QRect(0, 20, 81, 31))
        self.label_91.setObjectName("label_91")
        self.frame_63 = QtWidgets.QFrame(self.frame_62)
        self.frame_63.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_63.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.label_92 = QtWidgets.QLabel(self.frame_63)
        self.label_92.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.label_92.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_92.setObjectName("label_92")
        self.main_lb_state_4 = QtWidgets.QLabel(self.frame_21)
        self.main_lb_state_4.setGeometry(QtCore.QRect(40, 30, 201, 31))
        self.main_lb_state_4.setObjectName("main_lb_state_4")
        self.m_frame.raise_()
        self.main_lb_Date.raise_()
        self.main_lb_time.raise_()
        self.label_4.raise_()
        self.frame_4.raise_()
        self.frame_21.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.main_lb_Date.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:8pt;\">Date</span></p></body></html>"))
        self.main_lb_time.setText(_translate("Frame", "Time"))
        self.main_lb_program.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Program: </span></p></body></html>"))
        self.main_lb_state.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">State: </span></p></body></html>"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">X: </span></p></body></html>"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Y:</span></p></body></html>"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Drill nº:</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Frame", "Z"))
        self.pushButton_5.setText(_translate("Frame", "Drill"))
        self.label_6.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Emergency</span></p></body></html>"))
        self.label_8.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">B_Start</span></p></body></html>"))
        self.label_10.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">S_P</span></p></body></html>"))
        self.label_12.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a0</span></p></body></html>"))
        self.label_24.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a2</span></p></body></html>"))
        self.label_26.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a3</span></p></body></html>"))
        self.label_28.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a1</span></p></body></html>"))
        self.label_30.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C_Error</span></p></body></html>"))
        self.label_32.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C_Reach</span></p></body></html>"))
        self.label_18.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Yellow L.</span></p></body></html>"))
        self.label_34.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Drill</span></p></body></html>"))
        self.label_36.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C Enable</span></p></body></html>"))
        self.label_38.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Green L.</span></p></body></html>"))
        self.label_40.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Red L.</span></p></body></html>"))
        self.label_42.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Z Cilinder</span></p></body></html>"))
        self.label_44.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Out Cilinder</span></p></body></html>"))
        self.main_lb_state_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Inputs: </span></p></body></html>"))
        self.main_lb_state_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Outputs: </span></p></body></html>"))
        self.label_45.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type1:</span></p></body></html>"))
        self.label_46.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_49.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type2:</span></p></body></html>"))
        self.label_50.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_51.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type3:</span></p></body></html>"))
        self.label_52.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_55.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type4:</span></p></body></html>"))
        self.label_56.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_65.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type7:</span></p></body></html>"))
        self.label_66.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_67.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type8:</span></p></body></html>"))
        self.label_68.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_69.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type5:</span></p></body></html>"))
        self.label_70.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_71.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type6:</span></p></body></html>"))
        self.label_72.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_89.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type9:</span></p></body></html>"))
        self.label_90.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_91.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type10:</span></p></body></html>"))
        self.label_92.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.main_lb_state_4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Piece Counter:</span></p></body></html>"))
