# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1656, 753)
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setGeometry(QtCore.QRect(60, 10, 661, 741))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lb_imgCam = QtWidgets.QLabel(self.frame_2)
        self.lb_imgCam.setGeometry(QtCore.QRect(10, 60, 640, 480))
        self.lb_imgCam.setText("")
        self.lb_imgCam.setObjectName("lb_imgCam")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(230, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.pbNext = QtWidgets.QPushButton(self.frame_2)
        self.pbNext.setGeometry(QtCore.QRect(190, 680, 191, 41))
        self.pbNext.setObjectName("pbNext")
        self.label_34 = QtWidgets.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(190, 640, 51, 16))
        self.label_34.setObjectName("label_34")
        self.lb_Ping = QtWidgets.QLabel(self.frame_2)
        self.lb_Ping.setGeometry(QtCore.QRect(240, 640, 101, 16))
        self.lb_Ping.setText("")
        self.lb_Ping.setObjectName("lb_Ping")
        self.frame_4 = QtWidgets.QFrame(Frame)
        self.frame_4.setGeometry(QtCore.QRect(1400, 170, 241, 471))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(20, 110, 51, 16))
        self.label_10.setObjectName("label_10")
        self.lb_m2_G1 = QtWidgets.QLabel(self.frame_4)
        self.lb_m2_G1.setGeometry(QtCore.QRect(80, 110, 51, 16))
        self.lb_m2_G1.setObjectName("lb_m2_G1")
        self.lb_m1_G1 = QtWidgets.QLabel(self.frame_4)
        self.lb_m1_G1.setGeometry(QtCore.QRect(80, 100, 51, 16))
        self.lb_m1_G1.setObjectName("lb_m1_G1")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.label_13.setObjectName("label_13")
        self.lb_m3_G1 = QtWidgets.QLabel(self.frame_4)
        self.lb_m3_G1.setGeometry(QtCore.QRect(80, 120, 51, 16))
        self.lb_m3_G1.setObjectName("lb_m3_G1")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(20, 120, 51, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(50, 90, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(20, 170, 51, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(50, 140, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(20, 150, 51, 16))
        self.label_20.setObjectName("label_20")
        self.lb_m1_G2 = QtWidgets.QLabel(self.frame_4)
        self.lb_m1_G2.setGeometry(QtCore.QRect(80, 150, 51, 16))
        self.lb_m1_G2.setObjectName("lb_m1_G2")
        self.lb_m3_G2 = QtWidgets.QLabel(self.frame_4)
        self.lb_m3_G2.setGeometry(QtCore.QRect(80, 170, 51, 16))
        self.lb_m3_G2.setObjectName("lb_m3_G2")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.label_21.setObjectName("label_21")
        self.lb_m2_G2 = QtWidgets.QLabel(self.frame_4)
        self.lb_m2_G2.setGeometry(QtCore.QRect(80, 160, 51, 16))
        self.lb_m2_G2.setObjectName("lb_m2_G2")
        self.lb_m2_G3 = QtWidgets.QLabel(self.frame_4)
        self.lb_m2_G3.setGeometry(QtCore.QRect(80, 210, 51, 16))
        self.lb_m2_G3.setObjectName("lb_m2_G3")
        self.label_22 = QtWidgets.QLabel(self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(20, 200, 51, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(20, 220, 51, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(20, 210, 51, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(50, 190, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lb_m1_G3 = QtWidgets.QLabel(self.frame_4)
        self.lb_m1_G3.setGeometry(QtCore.QRect(80, 200, 51, 16))
        self.lb_m1_G3.setObjectName("lb_m1_G3")
        self.lb_m3_G3 = QtWidgets.QLabel(self.frame_4)
        self.lb_m3_G3.setGeometry(QtCore.QRect(80, 220, 51, 16))
        self.lb_m3_G3.setObjectName("lb_m3_G3")
        self.lb_m2_G4 = QtWidgets.QLabel(self.frame_4)
        self.lb_m2_G4.setGeometry(QtCore.QRect(80, 260, 51, 16))
        self.lb_m2_G4.setObjectName("lb_m2_G4")
        self.lb_m1_G4 = QtWidgets.QLabel(self.frame_4)
        self.lb_m1_G4.setGeometry(QtCore.QRect(80, 250, 51, 16))
        self.lb_m1_G4.setObjectName("lb_m1_G4")
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(20, 270, 51, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setGeometry(QtCore.QRect(20, 250, 51, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(20, 260, 51, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_4)
        self.label_29.setGeometry(QtCore.QRect(50, 240, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.lb_m3_G4 = QtWidgets.QLabel(self.frame_4)
        self.lb_m3_G4.setGeometry(QtCore.QRect(80, 270, 51, 16))
        self.lb_m3_G4.setObjectName("lb_m3_G4")
        self.lb_m2_G5 = QtWidgets.QLabel(self.frame_4)
        self.lb_m2_G5.setGeometry(QtCore.QRect(80, 310, 51, 16))
        self.lb_m2_G5.setObjectName("lb_m2_G5")
        self.lb_m1_G5 = QtWidgets.QLabel(self.frame_4)
        self.lb_m1_G5.setGeometry(QtCore.QRect(80, 300, 51, 16))
        self.lb_m1_G5.setObjectName("lb_m1_G5")
        self.label_30 = QtWidgets.QLabel(self.frame_4)
        self.label_30.setGeometry(QtCore.QRect(20, 320, 51, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(20, 300, 51, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(20, 310, 51, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.frame_4)
        self.label_33.setGeometry(QtCore.QRect(50, 290, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.lb_m3_G5 = QtWidgets.QLabel(self.frame_4)
        self.lb_m3_G5.setGeometry(QtCore.QRect(80, 320, 51, 16))
        self.lb_m3_G5.setObjectName("lb_m3_G5")
        self.label_75 = QtWidgets.QLabel(self.frame_4)
        self.label_75.setGeometry(QtCore.QRect(70, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_75.setFont(font)
        self.label_75.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_75.setTextFormat(QtCore.Qt.AutoText)
        self.label_75.setScaledContents(False)
        self.label_75.setObjectName("label_75")
        self.lb_plc_start = QtWidgets.QLabel(self.frame_4)
        self.lb_plc_start.setGeometry(QtCore.QRect(120, 60, 51, 16))
        self.lb_plc_start.setObjectName("lb_plc_start")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.label_15.setObjectName("label_15")
        self.lb_plc_group = QtWidgets.QLabel(self.frame_4)
        self.lb_plc_group.setGeometry(QtCore.QRect(120, 40, 51, 16))
        self.lb_plc_group.setObjectName("lb_plc_group")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.label_14.setObjectName("label_14")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(1400, 10, 241, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.label_7.setObjectName("label_7")
        self.lb_m1 = QtWidgets.QLabel(self.frame)
        self.lb_m1.setGeometry(QtCore.QRect(70, 60, 51, 16))
        self.lb_m1.setObjectName("lb_m1")
        self.lb_m2 = QtWidgets.QLabel(self.frame)
        self.lb_m2.setGeometry(QtCore.QRect(70, 80, 51, 16))
        self.lb_m2.setObjectName("lb_m2")
        self.lb_m3 = QtWidgets.QLabel(self.frame)
        self.lb_m3.setGeometry(QtCore.QRect(70, 100, 51, 16))
        self.lb_m3.setObjectName("lb_m3")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.frame_3 = QtWidgets.QFrame(Frame)
        self.frame_3.setGeometry(QtCore.QRect(730, 10, 661, 741))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lb_img_pro = QtWidgets.QLabel(self.frame_3)
        self.lb_img_pro.setGeometry(QtCore.QRect(10, 60, 640, 480))
        self.lb_img_pro.setText("")
        self.lb_img_pro.setObjectName("lb_img_pro")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(260, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.pbReset = QtWidgets.QPushButton(self.frame_3)
        self.pbReset.setGeometry(QtCore.QRect(240, 600, 151, 41))
        self.pbReset.setObjectName("pbReset")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_3.setText(_translate("Frame", "Imagem Câmera"))
        self.pbNext.setText(_translate("Frame", "Start Image"))
        self.label_34.setText(_translate("Frame", "PING:"))
        self.label_10.setText(_translate("Frame", "Medida 2: "))
        self.lb_m2_G1.setText(_translate("Frame", "0 mm"))
        self.lb_m1_G1.setText(_translate("Frame", "0 mm"))
        self.label_13.setText(_translate("Frame", "Medida 1: "))
        self.lb_m3_G1.setText(_translate("Frame", "0 mm"))
        self.label_16.setText(_translate("Frame", "Medida 3: "))
        self.label_17.setText(_translate("Frame", "G1"))
        self.label_18.setText(_translate("Frame", "Medida 3: "))
        self.label_19.setText(_translate("Frame", "G2"))
        self.label_20.setText(_translate("Frame", "Medida 1: "))
        self.lb_m1_G2.setText(_translate("Frame", "0 mm"))
        self.lb_m3_G2.setText(_translate("Frame", "0 mm"))
        self.label_21.setText(_translate("Frame", "Medida 2: "))
        self.lb_m2_G2.setText(_translate("Frame", "0 mm"))
        self.lb_m2_G3.setText(_translate("Frame", "0 mm"))
        self.label_22.setText(_translate("Frame", "Medida 1: "))
        self.label_23.setText(_translate("Frame", "Medida 3: "))
        self.label_24.setText(_translate("Frame", "Medida 2: "))
        self.label_25.setText(_translate("Frame", "G3"))
        self.lb_m1_G3.setText(_translate("Frame", "0 mm"))
        self.lb_m3_G3.setText(_translate("Frame", "0 mm"))
        self.lb_m2_G4.setText(_translate("Frame", "0 mm"))
        self.lb_m1_G4.setText(_translate("Frame", "0 mm"))
        self.label_26.setText(_translate("Frame", "Medida 3: "))
        self.label_27.setText(_translate("Frame", "Medida 1: "))
        self.label_28.setText(_translate("Frame", "Medida 2: "))
        self.label_29.setText(_translate("Frame", "G4"))
        self.lb_m3_G4.setText(_translate("Frame", "0 mm"))
        self.lb_m2_G5.setText(_translate("Frame", "0 mm"))
        self.lb_m1_G5.setText(_translate("Frame", "0 mm"))
        self.label_30.setText(_translate("Frame", "Medida 3: "))
        self.label_31.setText(_translate("Frame", "Medida 1: "))
        self.label_32.setText(_translate("Frame", "Medida 2: "))
        self.label_33.setText(_translate("Frame", "G5"))
        self.lb_m3_G5.setText(_translate("Frame", "0 mm"))
        self.label_75.setText(_translate("Frame", "Dados no PLC"))
        self.lb_plc_start.setText(_translate("Frame", "Start"))
        self.label_15.setText(_translate("Frame", "Comando Start:"))
        self.lb_plc_group.setText(_translate("Frame", "G1"))
        self.label_14.setText(_translate("Frame", "Grupo a trabalhar:"))
        self.label_5.setText(_translate("Frame", "Medida 1: "))
        self.label_6.setText(_translate("Frame", "Medida 2: "))
        self.label_7.setText(_translate("Frame", "Medida 3: "))
        self.lb_m1.setText(_translate("Frame", "0 mm"))
        self.lb_m2.setText(_translate("Frame", "0 mm"))
        self.lb_m3.setText(_translate("Frame", "0 mm"))
        self.label_11.setText(_translate("Frame", "Informação Processada"))
        self.label_4.setText(_translate("Frame", "Imagem Processada"))
        self.pbReset.setText(_translate("Frame", "Reset"))

