# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1920, 1080)
        Frame.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(90, 145, 255, 255), stop:1 rgba(255, 255, 255, 255));")
        self.lb_Date = QtWidgets.QLabel(Frame)
        self.lb_Date.setGeometry(QtCore.QRect(1036, 500, 241, 16))
        self.lb_Date.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_Date.setObjectName("lb_Date")
        self.lb_time = QtWidgets.QLabel(Frame)
        self.lb_time.setGeometry(QtCore.QRect(1036, 470, 56, 16))
        self.lb_time.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_time.setObjectName("lb_time")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(960, 90, 371, 331))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/estLogo.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.m_frame = QtWidgets.QFrame(Frame)
        self.m_frame.setGeometry(QtCore.QRect(10, 10, 951, 621))
        self.m_frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.m_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.m_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m_frame.setLineWidth(0)
        self.m_frame.setMidLineWidth(4)
        self.m_frame.setObjectName("m_frame")
        self.frame_1 = QtWidgets.QFrame(self.m_frame)
        self.frame_1.setGeometry(QtCore.QRect(10, 30, 471, 561))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_1.setPalette(palette)
        self.frame_1.setAutoFillBackground(False)
        self.frame_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_1.setObjectName("frame_1")
        self.Img_label = QtWidgets.QLabel(self.frame_1)
        self.Img_label.setGeometry(QtCore.QRect(60, 100, 310, 310))
        self.Img_label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Img_label.setMouseTracking(True)
        self.Img_label.setText("")
        self.Img_label.setPixmap(QtGui.QPixmap("Images/pNewProd.bmp"))
        self.Img_label.setScaledContents(True)
        self.Img_label.setObjectName("Img_label")
        self.main_cross = QtWidgets.QLabel(self.frame_1)
        self.main_cross.setGeometry(QtCore.QRect(40, 80, 41, 41))
        self.main_cross.setText("")
        self.main_cross.setPixmap(QtGui.QPixmap("Images/1cross.png"))
        self.main_cross.setScaledContents(True)
        self.main_cross.setObjectName("main_cross")
        self.main_circle = QtWidgets.QLabel(self.frame_1)
        self.main_circle.setGeometry(QtCore.QRect(40, 80, 41, 41))
        self.main_circle.setText("")
        self.main_circle.setPixmap(QtGui.QPixmap("Images/circle_lGreen.png"))
        self.main_circle.setScaledContents(True)
        self.main_circle.setObjectName("main_circle")
        self.lb_programFixed = QtWidgets.QLabel(self.frame_1)
        self.lb_programFixed.setGeometry(QtCore.QRect(40, 10, 151, 41))
        self.lb_programFixed.setObjectName("lb_programFixed")
        self.slider_X = QtWidgets.QSlider(self.frame_1)
        self.slider_X.setGeometry(QtCore.QRect(60, 430, 311, 21))
        self.slider_X.setMaximum(100)
        self.slider_X.setOrientation(QtCore.Qt.Horizontal)
        self.slider_X.setObjectName("slider_X")
        self.slider_Y = QtWidgets.QSlider(self.frame_1)
        self.slider_Y.setGeometry(QtCore.QRect(390, 100, 21, 311))
        self.slider_Y.setMaximum(100)
        self.slider_Y.setOrientation(QtCore.Qt.Vertical)
        self.slider_Y.setInvertedAppearance(True)
        self.slider_Y.setObjectName("slider_Y")
        self.lb_program = QtWidgets.QLabel(self.frame_1)
        self.lb_program.setGeometry(QtCore.QRect(160, 10, 151, 41))
        self.lb_program.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_program.setObjectName("lb_program")
        self.buttonCartesianEnable = QtWidgets.QPushButton(self.frame_1)
        self.buttonCartesianEnable.setGeometry(QtCore.QRect(170, 480, 111, 41))
        self.buttonCartesianEnable.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonCartesianEnable.setText("CartesianEnable")
        self.buttonCartesianEnable.setIconSize(QtCore.QSize(51, 33))
        self.buttonCartesianEnable.setCheckable(True)
        self.buttonCartesianEnable.setAutoDefault(True)
        self.buttonCartesianEnable.setDefault(False)
        self.buttonCartesianEnable.setFlat(False)
        self.buttonCartesianEnable.setObjectName("buttonCartesianEnable")
        self.Img_label.raise_()
        self.main_circle.raise_()
        self.main_cross.raise_()
        self.lb_programFixed.raise_()
        self.slider_X.raise_()
        self.slider_Y.raise_()
        self.lb_program.raise_()
        self.buttonCartesianEnable.raise_()
        self.frame_2 = QtWidgets.QFrame(self.m_frame)
        self.frame_2.setGeometry(QtCore.QRect(490, 30, 451, 371))
        self.frame_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lb_stateFixed = QtWidgets.QLabel(self.frame_2)
        self.lb_stateFixed.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.lb_stateFixed.setObjectName("lb_stateFixed")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 90, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 31, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 131, 31))
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 250, 431, 111))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.buttonZ = QtWidgets.QPushButton(self.frame_3)
        self.buttonZ.setGeometry(QtCore.QRect(30, 20, 91, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonZ.sizePolicy().hasHeightForWidth())
        self.buttonZ.setSizePolicy(sizePolicy)
        self.buttonZ.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/arowDown.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Images/arowUp.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonZ.setIcon(icon)
        self.buttonZ.setIconSize(QtCore.QSize(70, 68))
        self.buttonZ.setCheckable(True)
        self.buttonZ.setAutoDefault(True)
        self.buttonZ.setDefault(False)
        self.buttonZ.setFlat(False)
        self.buttonZ.setObjectName("buttonZ")
        self.buttonDrill = QtWidgets.QPushButton(self.frame_3)
        self.buttonDrill.setGeometry(QtCore.QRect(140, 20, 101, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDrill.sizePolicy().hasHeightForWidth())
        self.buttonDrill.setSizePolicy(sizePolicy)
        self.buttonDrill.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Drill1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("Images/Drill2.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonDrill.setIcon(icon1)
        self.buttonDrill.setIconSize(QtCore.QSize(70, 67))
        self.buttonDrill.setCheckable(True)
        self.buttonDrill.setAutoDefault(True)
        self.buttonDrill.setDefault(False)
        self.buttonDrill.setFlat(False)
        self.buttonDrill.setObjectName("buttonDrill")
        self.lb_state = QtWidgets.QLabel(self.frame_2)
        self.lb_state.setGeometry(QtCore.QRect(100, 14, 151, 41))
        self.lb_state.setStyleSheet("font: 87 14pt \"Arial Black\";")
        self.lb_state.setObjectName("lb_state")
        self.lb_X = QtWidgets.QLabel(self.frame_2)
        self.lb_X.setGeometry(QtCore.QRect(70, 87, 91, 31))
        self.lb_X.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.lb_X.setObjectName("lb_X")
        self.lb_Y = QtWidgets.QLabel(self.frame_2)
        self.lb_Y.setGeometry(QtCore.QRect(70, 120, 91, 31))
        self.lb_Y.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.lb_Y.setObjectName("lb_Y")
        self.lb_drillNumber = QtWidgets.QLabel(self.frame_2)
        self.lb_drillNumber.setGeometry(QtCore.QRect(130, 209, 31, 31))
        self.lb_drillNumber.setStyleSheet("font: 87 12pt \"Arial Black\";")
        self.lb_drillNumber.setObjectName("lb_drillNumber")
        self.buttonTeach = QtWidgets.QPushButton(self.frame_2)
        self.buttonTeach.setGeometry(QtCore.QRect(320, 100, 111, 41))
        self.buttonTeach.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonTeach.setText("Teach")
        self.buttonTeach.setIconSize(QtCore.QSize(51, 33))
        self.buttonTeach.setAutoDefault(True)
        self.buttonTeach.setDefault(False)
        self.buttonTeach.setFlat(False)
        self.buttonTeach.setObjectName("buttonTeach")
        self.buttonNextDrill = QtWidgets.QPushButton(self.frame_2)
        self.buttonNextDrill.setGeometry(QtCore.QRect(320, 150, 111, 41))
        self.buttonNextDrill.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonNextDrill.setText("Next Drill")
        self.buttonNextDrill.setIconSize(QtCore.QSize(51, 33))
        self.buttonNextDrill.setAutoDefault(True)
        self.buttonNextDrill.setDefault(False)
        self.buttonNextDrill.setFlat(False)
        self.buttonNextDrill.setObjectName("buttonNextDrill")
        self.buttonEndTeach = QtWidgets.QPushButton(self.frame_2)
        self.buttonEndTeach.setGeometry(QtCore.QRect(320, 200, 111, 41))
        self.buttonEndTeach.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonEndTeach.setText("End Teach")
        self.buttonEndTeach.setIconSize(QtCore.QSize(51, 33))
        self.buttonEndTeach.setAutoDefault(True)
        self.buttonEndTeach.setDefault(False)
        self.buttonEndTeach.setFlat(False)
        self.buttonEndTeach.setObjectName("buttonEndTeach")
        self.frame = QtWidgets.QFrame(self.m_frame)
        self.frame.setGeometry(QtCore.QRect(490, 400, 451, 101))
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.buttonManual = QtWidgets.QPushButton(self.frame)
        self.buttonManual.setGeometry(QtCore.QRect(40, 50, 111, 41))
        self.buttonManual.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));\n"
"")
        self.buttonManual.setText("Manual")
        self.buttonManual.setIconSize(QtCore.QSize(51, 33))
        self.buttonManual.setCheckable(True)
        self.buttonManual.setChecked(False)
        self.buttonManual.setAutoDefault(True)
        self.buttonManual.setDefault(False)
        self.buttonManual.setFlat(False)
        self.buttonManual.setObjectName("buttonManual")
        self.buttonInOut = QtWidgets.QPushButton(self.frame)
        self.buttonInOut.setGeometry(QtCore.QRect(160, 50, 111, 41))
        self.buttonInOut.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonInOut.setText("In/ Out")
        self.buttonInOut.setIconSize(QtCore.QSize(51, 33))
        self.buttonInOut.setAutoDefault(False)
        self.buttonInOut.setDefault(False)
        self.buttonInOut.setFlat(False)
        self.buttonInOut.setObjectName("buttonInOut")
        self.buttonData = QtWidgets.QPushButton(self.frame)
        self.buttonData.setGeometry(QtCore.QRect(280, 50, 111, 41))
        self.buttonData.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonData.setText("Data")
        self.buttonData.setIconSize(QtCore.QSize(51, 33))
        self.buttonData.setAutoDefault(False)
        self.buttonData.setDefault(False)
        self.buttonData.setFlat(False)
        self.buttonData.setObjectName("buttonData")
        self.loginFrame = QtWidgets.QFrame(self.frame)
        self.loginFrame.setGeometry(QtCore.QRect(150, 0, 301, 101))
        self.loginFrame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(150, 185, 255, 255), stop:1 rgba(169, 198, 255, 255));")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setMidLineWidth(4)
        self.loginFrame.setObjectName("loginFrame")
        self.lineEdit = QtWidgets.QLineEdit(self.loginFrame)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 171, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.loginFrame)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 161, 16))
        self.label_5.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"")
        self.label_5.setObjectName("label_5")
        self.buttonLogin = QtWidgets.QPushButton(self.loginFrame)
        self.buttonLogin.setGeometry(QtCore.QRect(210, 50, 71, 31))
        self.buttonLogin.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));\n"
"")
        self.buttonLogin.setText("Enter")
        self.buttonLogin.setIconSize(QtCore.QSize(51, 33))
        self.buttonLogin.setCheckable(False)
        self.buttonLogin.setAutoDefault(True)
        self.buttonLogin.setDefault(False)
        self.buttonLogin.setFlat(False)
        self.buttonLogin.setObjectName("buttonLogin")
        self.buttonStep = QtWidgets.QPushButton(self.m_frame)
        self.buttonStep.setGeometry(QtCore.QRect(530, 530, 111, 41))
        self.buttonStep.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonStep.setText("Step")
        self.buttonStep.setIconSize(QtCore.QSize(51, 33))
        self.buttonStep.setAutoDefault(True)
        self.buttonStep.setDefault(False)
        self.buttonStep.setFlat(False)
        self.buttonStep.setObjectName("buttonStep")
        self.frameInOut = QtWidgets.QFrame(Frame)
        self.frameInOut.setEnabled(True)
        self.frameInOut.setGeometry(QtCore.QRect(1290, 10, 441, 621))
        self.frameInOut.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frameInOut.setFrameShape(QtWidgets.QFrame.Box)
        self.frameInOut.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameInOut.setLineWidth(0)
        self.frameInOut.setMidLineWidth(4)
        self.frameInOut.setObjectName("frameInOut")
        self.frame_5 = QtWidgets.QFrame(self.frameInOut)
        self.frame_5.setGeometry(QtCore.QRect(40, 70, 151, 51))
        self.frame_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lb_inp0 = QtWidgets.QLabel(self.frame_5)
        self.lb_inp0.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp0.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp0.setText("")
        self.lb_inp0.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp0.setScaledContents(True)
        self.lb_inp0.setObjectName("lb_inp0")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.frame_6 = QtWidgets.QFrame(self.frameInOut)
        self.frame_6.setGeometry(QtCore.QRect(40, 130, 151, 51))
        self.frame_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lb_inp1 = QtWidgets.QLabel(self.frame_6)
        self.lb_inp1.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp1.setText("")
        self.lb_inp1.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp1.setScaledContents(True)
        self.lb_inp1.setObjectName("lb_inp1")
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.frame_7 = QtWidgets.QFrame(self.frameInOut)
        self.frame_7.setGeometry(QtCore.QRect(40, 190, 151, 51))
        self.frame_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lb_inp2 = QtWidgets.QLabel(self.frame_7)
        self.lb_inp2.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp2.setText("")
        self.lb_inp2.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp2.setScaledContents(True)
        self.lb_inp2.setObjectName("lb_inp2")
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.frame_8 = QtWidgets.QFrame(self.frameInOut)
        self.frame_8.setGeometry(QtCore.QRect(40, 250, 151, 51))
        self.frame_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.lb_inp3 = QtWidgets.QLabel(self.frame_8)
        self.lb_inp3.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp3.setText("")
        self.lb_inp3.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp3.setScaledContents(True)
        self.lb_inp3.setObjectName("lb_inp3")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_12.setObjectName("label_12")
        self.frame_9 = QtWidgets.QFrame(self.frameInOut)
        self.frame_9.setGeometry(QtCore.QRect(40, 370, 151, 51))
        self.frame_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lb_inp5 = QtWidgets.QLabel(self.frame_9)
        self.lb_inp5.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp5.setText("")
        self.lb_inp5.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp5.setScaledContents(True)
        self.lb_inp5.setObjectName("lb_inp5")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_24.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_24.setObjectName("label_24")
        self.frame_10 = QtWidgets.QFrame(self.frameInOut)
        self.frame_10.setGeometry(QtCore.QRect(40, 430, 151, 51))
        self.frame_10.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.lb_inp6 = QtWidgets.QLabel(self.frame_10)
        self.lb_inp6.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp6.setText("")
        self.lb_inp6.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp6.setScaledContents(True)
        self.lb_inp6.setObjectName("lb_inp6")
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        self.label_26.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_26.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_26.setObjectName("label_26")
        self.frame_12 = QtWidgets.QFrame(self.frameInOut)
        self.frame_12.setGeometry(QtCore.QRect(40, 310, 151, 51))
        self.frame_12.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.lb_inp4 = QtWidgets.QLabel(self.frame_12)
        self.lb_inp4.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp4.setText("")
        self.lb_inp4.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp4.setScaledContents(True)
        self.lb_inp4.setObjectName("lb_inp4")
        self.label_28 = QtWidgets.QLabel(self.frame_12)
        self.label_28.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_28.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_28.setObjectName("label_28")
        self.frame_13 = QtWidgets.QFrame(self.frameInOut)
        self.frame_13.setGeometry(QtCore.QRect(40, 490, 151, 51))
        self.frame_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.lb_inp7 = QtWidgets.QLabel(self.frame_13)
        self.lb_inp7.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp7.setText("")
        self.lb_inp7.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp7.setScaledContents(True)
        self.lb_inp7.setObjectName("lb_inp7")
        self.label_30 = QtWidgets.QLabel(self.frame_13)
        self.label_30.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_30.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_30.setObjectName("label_30")
        self.frame_14 = QtWidgets.QFrame(self.frameInOut)
        self.frame_14.setGeometry(QtCore.QRect(40, 550, 151, 51))
        self.frame_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.lb_inp8 = QtWidgets.QLabel(self.frame_14)
        self.lb_inp8.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_inp8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_inp8.setText("")
        self.lb_inp8.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_inp8.setScaledContents(True)
        self.lb_inp8.setObjectName("lb_inp8")
        self.label_32 = QtWidgets.QLabel(self.frame_14)
        self.label_32.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_32.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_32.setObjectName("label_32")
        self.frame_11 = QtWidgets.QFrame(self.frameInOut)
        self.frame_11.setGeometry(QtCore.QRect(260, 130, 151, 51))
        self.frame_11.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.lb_out1 = QtWidgets.QLabel(self.frame_11)
        self.lb_out1.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out1.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out1.setText("")
        self.lb_out1.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out1.setScaledContents(True)
        self.lb_out1.setObjectName("lb_out1")
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_18.setObjectName("label_18")
        self.frame_15 = QtWidgets.QFrame(self.frameInOut)
        self.frame_15.setGeometry(QtCore.QRect(260, 370, 151, 51))
        self.frame_15.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.lb_out5 = QtWidgets.QLabel(self.frame_15)
        self.lb_out5.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out5.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out5.setText("")
        self.lb_out5.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out5.setScaledContents(True)
        self.lb_out5.setObjectName("lb_out5")
        self.label_34 = QtWidgets.QLabel(self.frame_15)
        self.label_34.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_34.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_34.setObjectName("label_34")
        self.frame_16 = QtWidgets.QFrame(self.frameInOut)
        self.frame_16.setGeometry(QtCore.QRect(260, 430, 151, 51))
        self.frame_16.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.lb_out6 = QtWidgets.QLabel(self.frame_16)
        self.lb_out6.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out6.setText("")
        self.lb_out6.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out6.setScaledContents(True)
        self.lb_out6.setObjectName("lb_out6")
        self.label_36 = QtWidgets.QLabel(self.frame_16)
        self.label_36.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_36.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_36.setObjectName("label_36")
        self.frame_17 = QtWidgets.QFrame(self.frameInOut)
        self.frame_17.setGeometry(QtCore.QRect(260, 190, 151, 51))
        self.frame_17.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.lb_out2 = QtWidgets.QLabel(self.frame_17)
        self.lb_out2.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out2.setText("")
        self.lb_out2.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out2.setScaledContents(True)
        self.lb_out2.setObjectName("lb_out2")
        self.label_38 = QtWidgets.QLabel(self.frame_17)
        self.label_38.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_38.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_38.setObjectName("label_38")
        self.frame_18 = QtWidgets.QFrame(self.frameInOut)
        self.frame_18.setGeometry(QtCore.QRect(260, 70, 151, 51))
        self.frame_18.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.lb_out0 = QtWidgets.QLabel(self.frame_18)
        self.lb_out0.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out0.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out0.setText("")
        self.lb_out0.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out0.setScaledContents(True)
        self.lb_out0.setObjectName("lb_out0")
        self.label_40 = QtWidgets.QLabel(self.frame_18)
        self.label_40.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_40.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_40.setObjectName("label_40")
        self.frame_19 = QtWidgets.QFrame(self.frameInOut)
        self.frame_19.setGeometry(QtCore.QRect(260, 310, 151, 51))
        self.frame_19.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.lb_out4 = QtWidgets.QLabel(self.frame_19)
        self.lb_out4.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out4.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out4.setText("")
        self.lb_out4.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out4.setScaledContents(True)
        self.lb_out4.setObjectName("lb_out4")
        self.label_42 = QtWidgets.QLabel(self.frame_19)
        self.label_42.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_42.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_42.setObjectName("label_42")
        self.frame_20 = QtWidgets.QFrame(self.frameInOut)
        self.frame_20.setGeometry(QtCore.QRect(260, 250, 151, 51))
        self.frame_20.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.lb_out3 = QtWidgets.QLabel(self.frame_20)
        self.lb_out3.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lb_out3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.lb_out3.setText("")
        self.lb_out3.setPixmap(QtGui.QPixmap("Images/circle_dGreen.png"))
        self.lb_out3.setScaledContents(True)
        self.lb_out3.setObjectName("lb_out3")
        self.label_44 = QtWidgets.QLabel(self.frame_20)
        self.label_44.setGeometry(QtCore.QRect(50, 0, 101, 41))
        self.label_44.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_44.setObjectName("label_44")
        self.main_lb_state_2 = QtWidgets.QLabel(self.frameInOut)
        self.main_lb_state_2.setGeometry(QtCore.QRect(40, 20, 111, 31))
        self.main_lb_state_2.setObjectName("main_lb_state_2")
        self.main_lb_state_3 = QtWidgets.QLabel(self.frameInOut)
        self.main_lb_state_3.setGeometry(QtCore.QRect(260, 20, 111, 31))
        self.main_lb_state_3.setObjectName("main_lb_state_3")
        self.buttonInOutClose = QtWidgets.QPushButton(self.frameInOut)
        self.buttonInOutClose.setGeometry(QtCore.QRect(260, 540, 151, 61))
        self.buttonInOutClose.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonInOutClose.setText("Close")
        self.buttonInOutClose.setIconSize(QtCore.QSize(51, 33))
        self.buttonInOutClose.setAutoDefault(False)
        self.buttonInOutClose.setDefault(False)
        self.buttonInOutClose.setFlat(False)
        self.buttonInOutClose.setObjectName("buttonInOutClose")
        self.frameCounter = QtWidgets.QFrame(Frame)
        self.frameCounter.setGeometry(QtCore.QRect(10, 630, 951, 351))
        self.frameCounter.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frameCounter.setFrameShape(QtWidgets.QFrame.Box)
        self.frameCounter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameCounter.setMidLineWidth(4)
        self.frameCounter.setObjectName("frameCounter")
        self.frame_23 = QtWidgets.QFrame(self.frameCounter)
        self.frame_23.setGeometry(QtCore.QRect(40, 90, 261, 71))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_45 = QtWidgets.QLabel(self.frame_23)
        self.label_45.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_45.setObjectName("label_45")
        self.frame_22 = QtWidgets.QFrame(self.frame_23)
        self.frame_22.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_22.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.lb_Counter1 = QtWidgets.QLabel(self.frame_22)
        self.lb_Counter1.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter1.setObjectName("lb_Counter1")
        self.frame_24 = QtWidgets.QFrame(self.frameCounter)
        self.frame_24.setGeometry(QtCore.QRect(40, 150, 261, 71))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_49 = QtWidgets.QLabel(self.frame_24)
        self.label_49.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_49.setObjectName("label_49")
        self.frame_26 = QtWidgets.QFrame(self.frame_24)
        self.frame_26.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_26.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.lb_Counter2 = QtWidgets.QLabel(self.frame_26)
        self.lb_Counter2.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter2.setObjectName("lb_Counter2")
        self.frame_27 = QtWidgets.QFrame(self.frameCounter)
        self.frame_27.setGeometry(QtCore.QRect(40, 210, 261, 71))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_51 = QtWidgets.QLabel(self.frame_27)
        self.label_51.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_51.setObjectName("label_51")
        self.frame_28 = QtWidgets.QFrame(self.frame_27)
        self.frame_28.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_28.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.lb_Counter3 = QtWidgets.QLabel(self.frame_28)
        self.lb_Counter3.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter3.setObjectName("lb_Counter3")
        self.frame_29 = QtWidgets.QFrame(self.frameCounter)
        self.frame_29.setGeometry(QtCore.QRect(40, 270, 261, 71))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.label_55 = QtWidgets.QLabel(self.frame_29)
        self.label_55.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_55.setObjectName("label_55")
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_31.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.lb_Counter4 = QtWidgets.QLabel(self.frame_31)
        self.lb_Counter4.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter4.setObjectName("lb_Counter4")
        self.frame_32 = QtWidgets.QFrame(self.frameCounter)
        self.frame_32.setGeometry(QtCore.QRect(300, 210, 261, 71))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_65 = QtWidgets.QLabel(self.frame_32)
        self.label_65.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_65.setObjectName("label_65")
        self.frame_34 = QtWidgets.QFrame(self.frame_32)
        self.frame_34.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_34.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.lb_Counter7 = QtWidgets.QLabel(self.frame_34)
        self.lb_Counter7.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter7.setObjectName("lb_Counter7")
        self.frame_36 = QtWidgets.QFrame(self.frameCounter)
        self.frame_36.setGeometry(QtCore.QRect(300, 270, 261, 71))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.label_67 = QtWidgets.QLabel(self.frame_36)
        self.label_67.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_67.setObjectName("label_67")
        self.frame_38 = QtWidgets.QFrame(self.frame_36)
        self.frame_38.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_38.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.lb_Counter8 = QtWidgets.QLabel(self.frame_38)
        self.lb_Counter8.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter8.setObjectName("lb_Counter8")
        self.frame_40 = QtWidgets.QFrame(self.frameCounter)
        self.frame_40.setGeometry(QtCore.QRect(300, 90, 261, 71))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.label_69 = QtWidgets.QLabel(self.frame_40)
        self.label_69.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_69.setObjectName("label_69")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_41.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.lb_Counter5 = QtWidgets.QLabel(self.frame_41)
        self.lb_Counter5.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter5.setObjectName("lb_Counter5")
        self.frame_42 = QtWidgets.QFrame(self.frameCounter)
        self.frame_42.setGeometry(QtCore.QRect(300, 150, 261, 71))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.label_71 = QtWidgets.QLabel(self.frame_42)
        self.label_71.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_71.setObjectName("label_71")
        self.frame_43 = QtWidgets.QFrame(self.frame_42)
        self.frame_43.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_43.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.lb_Counter6 = QtWidgets.QLabel(self.frame_43)
        self.lb_Counter6.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter6.setObjectName("lb_Counter6")
        self.frame_44 = QtWidgets.QFrame(self.frameCounter)
        self.frame_44.setGeometry(QtCore.QRect(560, 90, 261, 71))
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.label_89 = QtWidgets.QLabel(self.frame_44)
        self.label_89.setGeometry(QtCore.QRect(0, 20, 71, 31))
        self.label_89.setObjectName("label_89")
        self.frame_61 = QtWidgets.QFrame(self.frame_44)
        self.frame_61.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_61.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.lb_Counter9 = QtWidgets.QLabel(self.frame_61)
        self.lb_Counter9.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter9.setObjectName("lb_Counter9")
        self.frame_62 = QtWidgets.QFrame(self.frameCounter)
        self.frame_62.setGeometry(QtCore.QRect(560, 150, 261, 71))
        self.frame_62.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_62.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_62.setObjectName("frame_62")
        self.label_91 = QtWidgets.QLabel(self.frame_62)
        self.label_91.setGeometry(QtCore.QRect(0, 20, 81, 31))
        self.label_91.setObjectName("label_91")
        self.frame_63 = QtWidgets.QFrame(self.frame_62)
        self.frame_63.setGeometry(QtCore.QRect(90, 10, 151, 51))
        self.frame_63.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.586158, y1:0.671, x2:0.593, y2:1, stop:0 rgba(0, 0, 127, 255), stop:1 rgba(85, 0, 255, 255));")
        self.frame_63.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_63.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_63.setObjectName("frame_63")
        self.lb_Counter10 = QtWidgets.QLabel(self.frame_63)
        self.lb_Counter10.setGeometry(QtCore.QRect(10, 0, 131, 41))
        self.lb_Counter10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 87 10pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lb_Counter10.setObjectName("lb_Counter10")
        self.main_lb_state_4 = QtWidgets.QLabel(self.frameCounter)
        self.main_lb_state_4.setGeometry(QtCore.QRect(40, 30, 201, 31))
        self.main_lb_state_4.setObjectName("main_lb_state_4")
        self.buttonCounterClose = QtWidgets.QPushButton(self.frameCounter)
        self.buttonCounterClose.setGeometry(QtCore.QRect(780, 270, 151, 61))
        self.buttonCounterClose.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonCounterClose.setText("Close")
        self.buttonCounterClose.setIconSize(QtCore.QSize(51, 33))
        self.buttonCounterClose.setAutoDefault(False)
        self.buttonCounterClose.setDefault(False)
        self.buttonCounterClose.setFlat(False)
        self.buttonCounterClose.setObjectName("buttonCounterClose")
        self.buttonReport = QtWidgets.QPushButton(self.frameCounter)
        self.buttonReport.setGeometry(QtCore.QRect(600, 270, 151, 61))
        self.buttonReport.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonReport.setText("Report")
        self.buttonReport.setIconSize(QtCore.QSize(51, 33))
        self.buttonReport.setAutoDefault(False)
        self.buttonReport.setDefault(False)
        self.buttonReport.setFlat(False)
        self.buttonReport.setObjectName("buttonReport")
        self.warningFrame = QtWidgets.QFrame(Frame)
        self.warningFrame.setGeometry(QtCore.QRect(1280, 670, 551, 281))
        self.warningFrame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.warningFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.warningFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.warningFrame.setLineWidth(0)
        self.warningFrame.setMidLineWidth(4)
        self.warningFrame.setObjectName("warningFrame")
        self.label_16 = QtWidgets.QLabel(self.warningFrame)
        self.label_16.setGeometry(QtCore.QRect(60, 70, 151, 141))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("Images/alert.gif"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(self.warningFrame)
        self.label_19.setGeometry(QtCore.QRect(270, 40, 211, 61))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.warningFrame)
        self.label_20.setGeometry(QtCore.QRect(270, 130, 201, 41))
        self.label_20.setObjectName("label_20")
        self.buttonWarningClose = QtWidgets.QPushButton(self.warningFrame)
        self.buttonWarningClose.setGeometry(QtCore.QRect(380, 200, 151, 61))
        self.buttonWarningClose.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.528, y1:1, x2:0.472, y2:0.00568182, stop:0 rgba(138, 138, 138, 255), stop:1 rgba(208, 208, 208, 255));")
        self.buttonWarningClose.setText("Close")
        self.buttonWarningClose.setIconSize(QtCore.QSize(51, 33))
        self.buttonWarningClose.setAutoDefault(False)
        self.buttonWarningClose.setDefault(False)
        self.buttonWarningClose.setFlat(False)
        self.buttonWarningClose.setObjectName("buttonWarningClose")
        self.m_frame.raise_()
        self.lb_Date.raise_()
        self.lb_time.raise_()
        self.label_4.raise_()
        self.frameInOut.raise_()
        self.frameCounter.raise_()
        self.warningFrame.raise_()

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.lb_Date.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:8pt;\">Date</span></p></body></html>"))
        self.lb_time.setText(_translate("Frame", "Time"))
        self.lb_programFixed.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Program: </span></p></body></html>"))
        self.lb_program.setText(_translate("Frame", "<html><head/><body><p>0</p></body></html>"))
        self.lb_stateFixed.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">State: </span></p></body></html>"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">X:</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Y:</span></p></body></html>"))
        self.label_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Drill nº:</span></p></body></html>"))
        self.buttonZ.setText(_translate("Frame", "Z"))
        self.buttonDrill.setText(_translate("Frame", "Drill"))
        self.lb_state.setText(_translate("Frame", "<html><head/><body><p>NA</p></body></html>"))
        self.lb_X.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">0</span></p><p><br/></p></body></html>"))
        self.lb_Y.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">0</span></p><p><br/></p></body></html>"))
        self.lb_drillNumber.setText(_translate("Frame", "<html><head/><body><p>0</p></body></html>"))
        self.label_5.setText(_translate("Frame", "Insert PIN:"))
        self.label_6.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Emergency</span></p></body></html>"))
        self.label_8.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">B_Start</span></p></body></html>"))
        self.label_10.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">S_P</span></p></body></html>"))
        self.label_12.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a0</span></p></body></html>"))
        self.label_24.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a2</span></p></body></html>"))
        self.label_26.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a3</span></p></body></html>"))
        self.label_28.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">a1</span></p></body></html>"))
        self.label_30.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C_Error</span></p></body></html>"))
        self.label_32.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C_Reach</span></p></body></html>"))
        self.label_18.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Yellow L.</span></p></body></html>"))
        self.label_34.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Drill</span></p></body></html>"))
        self.label_36.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">C Enable</span></p></body></html>"))
        self.label_38.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Green L.</span></p></body></html>"))
        self.label_40.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Red L.</span></p></body></html>"))
        self.label_42.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Z Cilinder</span></p></body></html>"))
        self.label_44.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">Out Cilinder</span></p></body></html>"))
        self.main_lb_state_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Inputs: </span></p></body></html>"))
        self.main_lb_state_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Outputs: </span></p></body></html>"))
        self.label_45.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type1:</span></p></body></html>"))
        self.lb_Counter1.setText(_translate("Frame", "<html><head/><body><p>0</p></body></html>"))
        self.label_49.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type2:</span></p></body></html>"))
        self.lb_Counter2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_51.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type3:</span></p></body></html>"))
        self.lb_Counter3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_55.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type4:</span></p></body></html>"))
        self.lb_Counter4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_65.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type7:</span></p></body></html>"))
        self.lb_Counter7.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_67.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type8:</span></p></body></html>"))
        self.lb_Counter8.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_69.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type5:</span></p></body></html>"))
        self.lb_Counter5.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_71.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type6:</span></p></body></html>"))
        self.lb_Counter6.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_89.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type9:</span></p></body></html>"))
        self.lb_Counter9.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.label_91.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Type10:</span></p></body></html>"))
        self.lb_Counter10.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">0</span></p></body></html>"))
        self.main_lb_state_4.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Piece Counter:</span></p></body></html>"))
        self.label_19.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600; text-decoration: underline; color:#ff0000;\">WARNING</span></p></body></html>"))
        self.label_20.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Machine Stopped</span></p></body></html>"))
